### ISSUE TITLE
create embryo doesn't produce tiff files

### ISSUE THREAD

**Issue by hpreiss** [alexblaessle/PyFRAP#8]
after choosing folder embryo data, embryo creationbutton only creates new folders but no tiffs
WARNING:There are no files of type tif in . This can lead to problems.

**Comment by alexblaessle** [comment]
This was a problem with the path handling in Windows, fiji macro calls in Windows and moving/removing files in Windows. That should have been fixed in commits https://github.com/alexblaessle/PyFRAP/commit/c8cef017b19fd6f1d72bd84d60b39a68cdd485ef - https://github.com/alexblaessle/PyFRAP/commit/341aa7bbbcd1f62dde3ba4b88f88084951a1afe3 .

@hpreiss , could you please confirm?

**Comment by alexblaessle** [comment]
Tested and works. Closed.
